### ISSUE TITLE
Issues with the note

### ISSUE THREAD

**Issue by zubairov** [elasticio/pipedrive-component#1]
Apparently note template on the deal is not merged properly:

![image](https://user-images.githubusercontent.com/56208/29776448-efb2b868-8c08-11e7-910f-b0d814bd8405.png)

values are there but on in the places where they should be

**Comment by hasenbanck** [comment]
I allready fixed that in a531a7a6811d1c620320ee1badbd3137cf20bdaa . I think you need to update the Repository on the elastic.io platform, which you are using. Are you using my old one in mviseDEV?

**Comment by zubairov** [comment]
What do you think we we externalize the note in the mapper and not to hard-code it in component?

**Comment by hasenbanck** [comment]
Have a look at #3 . I moved the note into a configurable field and you might just add it in the flow with the help of the mapper.

**Comment by zubairov** [comment]
Should be solved now
